In [1]:
# Dépendances du notebook
%pip install openpyxl==3.1.3 pandas==3.0.2 s3fs==2026.3.0 -q

Note: you may need to restart the kernel to use updated packages.

In [21]:
import pandas as pd
import requests

# 1. Charger le fichier CSV local
df_emplacement = pd.read_csv('https://minio.lab.sspcloud.fr/aissataa/MEDAS_Financial-Reporting/DATA/velib-emplacement-des-stations.csv', sep=';')

# 2. Récupérer les données temps réel via l'API
url_api = "https://opendata.paris.fr/api/explore/v2.1/catalog/datasets/velib-disponibilite-en-temps-reel/records?limit=20"
response = requests.get(url_api)
df_temps_reel = pd.json_normalize(response.json()['results'])

In [22]:
df_temps_reel

,stationcode,name,is_installed,capacity,numdocksavailable,numbikesavailable,mechanical,ebike,is_renting,is_returning,duedate,nom_arrondissement_communes,code_insee_commune,station_opening_hours,coordonnees_geo.lon,coordonnees_geo.lat
0,16107,Benjamin Godard - Victor Hugo,OUI,35,32,3,1,2,OUI,OUI,2026-05-12T13:23:03+00:00,Paris,75056,None,2.275725,48.865983
1,40001,Hôpital Mondor,OUI,28,1,27,6,21,OUI,OUI,2026-05-12T13:27:09+00:00,Créteil,94028,None,2.453745,48.798922
2,32304,Charcot - Benfleet,OUI,28,26,1,0,1,OUI,OUI,2026-05-12T13:26:34+00:00,Romainville,93063,None,2.440524,48.878370
3,11104,Charonne - Robert et Sonia Delaunay,OUI,20,20,0,0,0,OUI,OUI,2026-05-12T13:29:00+00:00,Paris,75056,None,2.392571,48.855908
4,8026,Messine - Place Du Pérou,OUI,12,1,11,5,6,OUI,OUI,2026-05-12T13:24:22+00:00,Paris,75056,None,2.315508,48.875448
5,7002,Vaneau - Sèvres,OUI,35,29,5,4,1,OUI,OUI,2026-05-12T13:32:02+00:00,Paris,75056,None,2.320422,48.848563
6,5110,Lacépède - Monge,OUI,23,13,10,1,9,OUI,OUI,2026-05-12T13:28:21+00:00,Paris,75056,None,2.351966,48.843893
7,6108,Saint-Romain - Cherche-Midi,OUI,17,14,3,3,0,OUI,OUI,2026-05-12T13:31:17+00:00,Paris,75056,None,2.321375,48.847082
8,42016,Pierre et Marie Curie - Maurice Thorez,OUI,27,26,1,0,1,OUI,OUI,2026-05-12T13:32:14+00:00,Ivry-sur-Seine,94041,None,2.376805,48.815802
9,25006,Place Nelson Mandela,OUI,22,21,1,1,0,OUI,OUI,2026-05-12T13:31:03+00:00,Rueil-Malmaison,92063,None,2.196167,48.862453
10,40011,Bas du Mont-Mesly,OUI,27,5,22,19,3,OUI,OUI,2026-05-12T13:32:50+00:00,Créteil,94028,None,2.460837,48.779751
11,17041,Guersant - Gouvion-Saint-Cyr,OUI,36,13,20,14,6,OUI,OUI,2026-05-12T13:32:23+00:00,Paris,75056,None,2.287667,48.882878
12,17026,Jouffroy d'Abbans - Wagram,OUI,40,35,4,1,3,OUI,OUI,2026-05-12T13:32:40+00:00,Paris,75056,None,2.301132,48.881973
13,12109,Mairie du 12ème,OUI,30,15,15,8,7,OUI,OUI,2026-05-12T13:32:42+00:00,Paris,75056,None,2.387555,48.840855
14,6021,Beaux-Arts - Bonaparte,OUI,20,2,18,13,5,OUI,OUI,2026-05-12T13:32:06+00:00,Paris,75056,None,2.334852,48.856452
15,15202,Bracion - Périphérique,OUI,30,29,1,1,0,OUI,OUI,2026-05-12T13:29:46+00:00,Paris,75056,None,2.300455,48.826104
16,13007,Le Brun - Gobelins,OUI,48,45,2,2,0,OUI,OUI,2026-05-12T13:30:52+00:00,Paris,75056,None,2.353468,48.835093
17,21108,Mairie de Clichy,OUI,51,40,9,5,4,OUI,OUI,2026-05-12T13:31:46+00:00,Clichy,92024,None,2.305935,48.903654
18,2022,Saint-Fiacre - Poissonière,OUI,35,7,28,7,21,OUI,OUI,2026-05-12T13:30:34+00:00,Paris,75056,None,2.345921,48.870829
19,19033,Cambrai - Benjamin Constant,OUI,43,31,12,6,6,OUI,OUI,2026-05-12T13:26:01+00:00,Paris,75056,None,2.381134,48.895947

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1511 entries, 0 to 1510
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Identifiant station             1511 non-null   int64
 1   Nom station                     1511 non-null   str
 2   Station en fonctionnement       1511 non-null   str
 3   Capacité de la station          1511 non-null   int64
 4   Nombre bornettes libres         1511 non-null   int64
 5   Nombre total vélos disponibles  1511 non-null   int64
 6   Vélos mécaniques disponibles    1511 non-null   int64
 7   Vélos électriques disponibles   1511 non-null   int64
 8   Borne de paiement disponible    1511 non-null   str
 9   Retour vélib possible           1511 non-null   str
 10  Actualisation de la donnée      1511 non-null   str
 11  Coordonnées géographiques       1511 non-null   str
 12  Nom communes équipées           1511 non-null   str
 13  Code INSEE communes équipées    1511 non-null   int64
dtypes: int64(7), str(7)
memory usage: 309.8 KB

In [9]:
df.head()

,Identifiant station,Nom station,Station en fonctionnement,Capacité de la station,Nombre bornettes libres,Nombre total vélos disponibles,Vélos mécaniques disponibles,Vélos électriques disponibles,Borne de paiement disponible,Retour vélib possible,Actualisation de la donnée,Coordonnées géographiques,Nom communes équipées,Code INSEE communes équipées
0,40001,Hôpital Mondor,OUI,28,1,27,7,20,OUI,OUI,2026-05-12T12:26:16+02:00,"48.798922410229, 2.4537451531298",Créteil,94028
1,8026,Messine - Place Du Pérou,OUI,12,4,8,1,7,OUI,OUI,2026-05-12T12:32:28+02:00,"48.875448033960744, 2.315508019010038",Paris,75056
2,7002,Vaneau - Sèvres,OUI,35,25,9,7,2,OUI,OUI,2026-05-12T12:30:47+02:00,"48.848563233059, 2.3204218259346",Paris,75056
3,5110,Lacépède - Monge,OUI,23,18,5,3,2,OUI,OUI,2026-05-12T12:27:29+02:00,"48.84389286531899, 2.3519663885235786",Paris,75056
4,6108,Saint-Romain - Cherche-Midi,OUI,17,16,1,1,0,OUI,OUI,2026-05-12T12:30:29+02:00,"48.84708159081946, 2.321374788880348",Paris,75056

In [8]:
# Les valeurs manquantes
df.isna().sum()

Identifiant station               0
Nom station                       0
Station en fonctionnement         0
Capacité de la station            0
Nombre bornettes libres           0
Nombre total vélos disponibles    0
Vélos mécaniques disponibles      0
Vélos électriques disponibles     0
Borne de paiement disponible      0
Retour vélib possible             0
Actualisation de la donnée        0
Coordonnées géographiques         0
Nom communes équipées             0
Code INSEE communes équipées      0
dtype: int64

In [11]:
# Supprimer les colonnes inutiles
df = df.drop(columns=['station_opening_hours'])
df

,Identifiant station,Nom station,Station en fonctionnement,Capacité de la station,Nombre bornettes libres,Nombre total vélos disponibles,Vélos mécaniques disponibles,Vélos électriques disponibles,Borne de paiement disponible,Retour vélib possible,Actualisation de la donnée,Coordonnées géographiques,Nom communes équipées,Code INSEE communes équipées
0,40001,Hôpital Mondor,OUI,28,1,27,7,20,OUI,OUI,2026-05-12T12:26:16+02:00,"48.798922410229, 2.4537451531298",Créteil,94028
1,8026,Messine - Place Du Pérou,OUI,12,4,8,1,7,OUI,OUI,2026-05-12T12:32:28+02:00,"48.875448033960744, 2.315508019010038",Paris,75056
2,7002,Vaneau - Sèvres,OUI,35,25,9,7,2,OUI,OUI,2026-05-12T12:30:47+02:00,"48.848563233059, 2.3204218259346",Paris,75056
3,5110,Lacépède - Monge,OUI,23,18,5,3,2,OUI,OUI,2026-05-12T12:27:29+02:00,"48.84389286531899, 2.3519663885235786",Paris,75056
4,6108,Saint-Romain - Cherche-Midi,OUI,17,16,1,1,0,OUI,OUI,2026-05-12T12:30:29+02:00,"48.84708159081946, 2.321374788880348",Paris,75056
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1506,15204,Square Bela Bartok,OUI,24,4,20,15,5,OUI,OUI,2026-05-12T12:32:34+02:00,"48.850984480382, 2.2844360220351",Paris,75056
1507,18043,Clichy - Place Blanche,OUI,20,18,2,0,2,OUI,OUI,2026-05-12T12:24:54+02:00,"48.883601088297, 2.3332237824798",Paris,75056
1508,9104,Caumartin - Provence,OUI,22,13,9,4,5,OUI,OUI,2026-05-12T12:32:35+02:00,"48.874422773426545, 2.3284685611724854",Paris,75056
1509,5202,Arbalète - Claude Bernard,OUI,34,21,12,4,8,OUI,OUI,2026-05-12T12:32:33+02:00,"48.840008992, 2.347522975107",Paris,75056
1510,8002,Gare Saint-Lazare - Cour du Havre,OUI,45,11,32,13,19,OUI,OUI,2026-05-12T12:32:36+02:00,"48.875674400851, 2.3265598341823",Paris,75056

In [23]:
# Changement de la colonne Actualisation de la donnée (string) en date
import pandas as pd

# 1. Conversion de la colonne en vrai format datetime
# Pandas gère le "T" automatiquement, pas besoin de faire un .replace()
df['Actualisation de la donnée'] = pd.to_datetime(df['Actualisation de la donnée'], errors='coerce')

# 2. Vérification du type (doit afficher datetime64[ns, UTC...])
print(df['Actualisation de la donnée'].dtype)

# 3. Si tu veux supprimer le "T" visuellement pour ton rapport Excel :
df['Actualisation_propre'] = df['Actualisation de la donnée'].dt.strftime('%d/%m/%Y %H:%M:%S')

ValueError: Mixed timezones detected. Pass utc=True in to_datetime or tz='UTC' in DatetimeIndex to convert to a common timezone.

In [17]:
df

,Identifiant station,Nom station,Station en fonctionnement,Capacité de la station,Nombre bornettes libres,Nombre total vélos disponibles,Vélos mécaniques disponibles,Vélos électriques disponibles,Borne de paiement disponible,Retour vélib possible,Actualisation de la donnée,Coordonnées géographiques,Nom communes équipées,Code INSEE communes équipées
0,40001,Hôpital Mondor,OUI,28,1,27,7,20,OUI,OUI,2026-05-12T12:26:16+02:00,"48.798922410229, 2.4537451531298",Créteil,94028
1,8026,Messine - Place Du Pérou,OUI,12,4,8,1,7,OUI,OUI,2026-05-12T12:32:28+02:00,"48.875448033960744, 2.315508019010038",Paris,75056
2,7002,Vaneau - Sèvres,OUI,35,25,9,7,2,OUI,OUI,2026-05-12T12:30:47+02:00,"48.848563233059, 2.3204218259346",Paris,75056
3,5110,Lacépède - Monge,OUI,23,18,5,3,2,OUI,OUI,2026-05-12T12:27:29+02:00,"48.84389286531899, 2.3519663885235786",Paris,75056
4,6108,Saint-Romain - Cherche-Midi,OUI,17,16,1,1,0,OUI,OUI,2026-05-12T12:30:29+02:00,"48.84708159081946, 2.321374788880348",Paris,75056
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1506,15204,Square Bela Bartok,OUI,24,4,20,15,5,OUI,OUI,2026-05-12T12:32:34+02:00,"48.850984480382, 2.2844360220351",Paris,75056
1507,18043,Clichy - Place Blanche,OUI,20,18,2,0,2,OUI,OUI,2026-05-12T12:24:54+02:00,"48.883601088297, 2.3332237824798",Paris,75056
1508,9104,Caumartin - Provence,OUI,22,13,9,4,5,OUI,OUI,2026-05-12T12:32:35+02:00,"48.874422773426545, 2.3284685611724854",Paris,75056
1509,5202,Arbalète - Claude Bernard,OUI,34,21,12,4,8,OUI,OUI,2026-05-12T12:32:33+02:00,"48.840008992, 2.347522975107",Paris,75056
1510,8002,Gare Saint-Lazare - Cour du Havre,OUI,45,11,32,13,19,OUI,OUI,2026-05-12T12:32:36+02:00,"48.875674400851, 2.3265598341823",Paris,75056

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1511 entries, 0 to 1510
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Identifiant station             1511 non-null   int64
 1   Nom station                     1511 non-null   str
 2   Station en fonctionnement       1511 non-null   str
 3   Capacité de la station          1511 non-null   int64
 4   Nombre bornettes libres         1511 non-null   int64
 5   Nombre total vélos disponibles  1511 non-null   int64
 6   Vélos mécaniques disponibles    1511 non-null   int64
 7   Vélos électriques disponibles   1511 non-null   int64
 8   Borne de paiement disponible    1511 non-null   str
 9   Retour vélib possible           1511 non-null   str
 10  Actualisation de la donnée      1511 non-null   str
 11  Coordonnées géographiques       1511 non-null   str
 12  Nom communes équipées           1511 non-null   str
 13  Code INSEE communes équipées    1511 non-null   int64
dtypes: int64(7), str(7)
memory usage: 309.8 KB